### ISSUE TITLE
pacstrap: copy pacman databases?

### ISSUE THREAD

**Issue by christianbundy** [archlinux/arch-install-scripts#5]
I've been doing lots of builds from source recently and (of course) pacstrap is a huge help for building in a clean chroot. I love that I can use my host's package cache, keyring, and mirror list, but I've noticed that since `pacmode=Sy` then pacstrap downloads `/var/lib/pacman/sync/*.db` over the network. **Would you merge a patch that adds an option to copy databases from the host?**

Here's what I have right now:

```diff
diff --git a/pacstrap.in b/pacstrap.in
index 703df11..4f44a04 100644
--- a/pacstrap.in
+++ b/pacstrap.in
@@ -15,7 +15,7 @@ m4_include(common)
 hostcache=0
 copykeyring=1
 copymirrorlist=1
-pacmode=-Sy
+pacmode=-S
 
 usage() {
   cat <<EOF
@@ -121,4 +121,8 @@ if (( copymirrorlist )); then
   cp -a /etc/pacman.d/mirrorlist "$newroot/etc/pacman.d/"
 fi
 
+# HACK: Use host databases instead of downloading new one.
+mkdir -p "$newroot/var/lib/pacman/sync"
+cp -a /var/lib/pacman/sync/*.db "$newroot/var/lib/pacman/sync/"
+
 # vim: et ts=2 sw=2 ft=sh:
```

If this is something you'd like to merge, how would you like to see it integrated?

**Comment by eli-schwartz** [comment]
I'm not sure I understand what the use case is here. pacstrap is intended to install Arch from scratch, brand-new and up to date; it hits up the network for the databases, then for the packages. There's a special exception for -U if you want exact control over the files used.

Why do you want to use the host databases? That isn't necessarily the right thing if the host hasn't synced just beforehand.

And it's definitely not the right thing if you're passing in a pacman.conf for use instead of the host default, because there's no guarantee that the conf file only contains databases that were previously copied from the host; one common use of pacstrap is to create chroots using the testing or staging repos, from a host running only the stable repos.

**Comment by christianbundy** [comment]
Thanks for the response! My use-case is that I'm building all of these dependencies from scratch, and by the time I'm running mkarchroot (which calls pacstrap) my database is up-to-date and I've already compiled all of the depends and makedepends. Since I'm already up-to-date and my dependencies are already built, I don't actually want pacstrap to hit the network -- I just want it to use my package cache.

**Comment by eli-schwartz** [comment]
In that case, it seems like there's a larger issue. You don't want it to hit up the network after pacstrap either (overwriting the packages you've built yourself), you want its pacman.conf to pull updates from your custom repo-add database.

Have you considered running a simple localhost server for your self-built packages, and using pacstrap with a custom pacman.conf pointing to that localhost server instead of the public mirror network?

**Comment by christianbundy** [comment]
> Have you considered running a simple localhost server for your self-built packages, and using pacstrap/mkarchroot with a custom pacman.conf pointing to that localhost server instead of the public mirror network?

I've considered it, but it seems silly to have a database that's a direct copy of all of the packages in my cache. For what it's worth, I'm on a device with constrained storage (64 GB) which makes lots of this a pain.

Are there scripts for managing a custom local repository, or would I need to write those by hand?

**Comment by eli-schwartz** [comment]
The "aurutils" AUR helper can do that.

If you're rebuilding the repo packages, their checksums will differ anyway and you cannot reinstall them using the official repo databases. pacman will raise a fatal error that the packages are corrupt, and offer you the opportunity to delete them from the cache before exiting.

So you would need to generate a database using `repo-add <repo>.db.tar.gz *.pkg.tar.zst` anyway and tell pacman.conf to use this, and the question is whether you're doing it for the host or just the chroot...

**Comment by christianbundy** [comment]
Thanks, I tried that but it looks like my repo needs to already have my 'depends' info, so it's a bit of a chicken and egg problem. I think maybe trying to turn my Arch install into a source-based OS is probably an exercise in futility. Thanks for all your help.

**Comment by eli-schwartz** [comment]
You'd essentially just bootstrap your custom versions of all packages, using the official packages to get started. Maybe add your repo as an overlay on top of core/extra/community until you've built enough to drop core/extra/community themselves.
